package bombaycinema.cameratimer;

import java.util.Stack;

/*
 * Object used to represent and process Time related elements of the application
 * @author Michael Murray
 * @version v2.0, 27/06/2016
 */
public class Time {
    private int hours = 0;
    private int minutes = 0;
    private int seconds = 0;

    /*
     * Constructor of the time object
     * @param hours - the hours of the time
     * @param minutes - the minutes of the time
     * @param seconds -  the seconds of the time
     */
    public Time(int hours, int minutes, int seconds){
        this.seconds = seconds;
        this.minutes = minutes;
        this.hours = hours;
        //adds minutes if the seconds element is longer than 60
        if (this.seconds >= 60){
            this.seconds -= 60;
            this.minutes++;
        }
        //adds hours if the minutes element is longer than 60
        if (this.minutes >= 60){
            this.minutes -= 60;
            //hours must be below 99
            if (this.hours <= 98){
                this.hours++;
            }
        }
    }

    /*
     * used for editing the time in the timer input fragment
     * @return the time as a stack element
     */
    public Stack<Integer> getAsStack(){
        boolean addToStack = false;
        Stack<Integer> tempStack = new Stack<Integer>();
        String tempString = getAsDoubleDigit(hours) + getAsDoubleDigit(minutes) + getAsDoubleDigit(seconds);
        for (int i = 0; i < 6; i++) {
            if (tempString.charAt(i) != '0'){
                addToStack = true;
            }
            if (addToStack == true){
                tempStack.add(Integer.parseInt(Character.toString(tempString.charAt(i))));
            }
        }
        return tempStack;
    }

    /*
     * resets the current time to 0 and recreates it based on the seconds given
     * @param seconds - the amount of seconds
     */
    public void secondsToTime(int seconds){
        resetTime();
        int tempSeconds = seconds;
        //loops until seconds is less than 60
        while (tempSeconds >= 60){
            if (tempSeconds >= 60){
                minutes++;
                tempSeconds -= 60;
            }
            if (minutes >= 60){
                hours++;
                minutes = 0;
            }
        }
        this.seconds = tempSeconds;
    }

    /*
     * increments the current time by 1 second
     * keeps seconds and minutes within range of 60
     */
    public void incrementTime(){
        seconds++;
        if (seconds >= 60){
            minutes++;
            seconds = 0;
        }
        if (minutes >= 60){
            hours++;
            minutes = 0;
        }
    }

    /*
     * resets all variables back to 0
     */
    public void resetTime(){
        hours = 0;
        minutes = 0;
        seconds = 0;
    }

    /*
     * converts the current time to a string
     * @return the string generated by the time
     */
    public String toString(){
        String tempString = getAsDoubleDigit(hours)+"h "+getAsDoubleDigit(minutes)+"m "+getAsDoubleDigit(seconds)+"s";
        return tempString;
    }

    /*
     * converts the current time all into seconds
     */
    public int toSeconds(){
        return (60*60*hours)+(minutes*60)+seconds;
    }

    /*
     * parses a string to create a time
     * @param time - the string used to represent the time
     */
    public void stringToTime(String time){
        hours = Integer.parseInt(time.substring(0, 2));
        minutes = Integer.parseInt(time.substring(4, 6));
        seconds = Integer.parseInt(time.substring(8, 10));
    }

    /*
     * takes an integer and converts it into a two digit string
     * @param number - the number to be converted
     * @return the string which represents the number
     */
    public static String getAsDoubleDigit(int number){
        String tempString = "";
        if ((number+"").length() <= 1){
            tempString += "0"+number;
        } else {
            tempString += number+"";
        }
        return tempString;
    }
}
